model_deployments:
  - name: huggingface/llama-3.1-8b-instruct
    model_name: meta/llama-3.1-8b-instruct
    tokenizer_name: meta/llama-3.1-8b-instruct
    max_sequence_length: 131072
    client_spec:
      class_name: "helm.clients.huggingface_client.HuggingFaceClient"
      args:
        pretrained_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
        torch_dtype: "float16"

  - name: huggingface/llama-3.2-3b-instruct
    model_name: meta/llama-3.2-3b-instruct
    tokenizer_name: meta/llama-3.2-3b-instruct
    max_sequence_length: 131072
    client_spec:
      class_name: "helm.clients.huggingface_client.HuggingFaceClient"
      args:
        pretrained_model_name_or_path: meta-llama/Llama-3.2-3B-Instruct
        torch_dtype: "float16"

  - name: huggingface/llama-3.2-1b-instruct
    model_name: meta/llama-3.2-1b-instruct
    tokenizer_name: meta/llama-3.2-1b-instruct
    max_sequence_length: 131072
    client_spec:
      class_name: "helm.clients.huggingface_client.HuggingFaceClient"
      args:
        pretrained_model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
        torch_dtype: "float16"
